[data-transition="none"]
== Block Scope

----
{
  let x = 0;
  // ---
}
----

[NOTE.speaker]
--
ES6 introduces sane scoping, that actual living humans can understand.

Declaring a variable with `let` rather than `var` introduces with block scope, and it is created and initialised at the point of declaration.  Compare this to the insane scoping of `var` which has function scope, is visible throughout the function regardless of where it is declared, and is only initialised once you get to the declaration.
--

[data-transition="none"]
=== Block Scope

----
{
  let x = 0;
  // ---
}
console.log(x); // ERROR!
----

[NOTE.speaker]
--
ES6 introduces sane scoping, that actual living humans can understand.

Declaring a variable with `let` rather than `var` introduces with block scope, and it is created and initialised at the point of declaration.  Compare this to the insane scoping of `var` which has function scope, is visible throughout the function regardless of where it is declared, and is only initialised once you get to the declaration.
--

----
{
  console.log(x); // ERROR
  // ---
  let x = 0;
  // ---
}
----

[NOTE.speaker]
--
ES6 introduces sane scoping, that actual living humans can understand.

Declaring a variable with `let` rather than `var` introduces with block scope, and it is created and initialised at the point of declaration.  Compare this to the insane scoping of `var` which has function scope, is visible throughout the function regardless of where it is declared, and is only initialised once you get to the declaration.

You know the problem with fake news right, that in order to counter it you have to repeat it, and that helps reenforce it?  I did have some examples in here with var, but I took them all out because I don't even want you to see them.

--

[data-transition="none"]
=== Block Scope

----

{
  let x = 0;
  // ---
}
----

[NOTE.speaker]
--
In all these little fragments, I've declared and initialised x in one.  You can also declare and then initialise them separately, but why would you want to do that?  Don't do that.

Block scoping also allows for shadowing, as you can in other languages, but again this is sane (or at least relatively so) and behaves in ways you probably already expect.
--

[data-transition="none"]
=== Block Scope

----
let x = 0;
// ---
{
  let x = "something else";
  // ---
}
// ---
----

[NOTE.speaker]
--
Shadowing in action.  As we come out of the block, the value we see for x is 0.  Try that with var and you'll see "something else", and it would almost certainly be wrong.
--

[data-transition="none"]
=== Block Scope

----
let x = "Hello";

const y = "World";

x = "Goodbye";
----

[NOTE.speaker]
--
Not only do we have this sensible block scoping via `let`, we now also have `const`.

Constants, created with `const`, are immutable, so we can't change the binding.  (In this sense it's more like a Java final or C# readonly than a C++ const.)
--

[data-transition="none"]
=== Block Scope

----
let x = "Hello";

const y = "World";

x = "Goodbye";

y = "Cruel World";  // ERROR
----

[NOTE.speaker]
--
Just by themselves, `let` and `const`, can make a really disproportionate difference.  Use them.  Purge `var` from your mind. Use `const` as often as you can  (Side note - Lisp bindings are lexically scoped and const. John McCarthy probably did have this programming thing figured out in the 50s) and use `let` when you really do need a variable.  That's probably less you often that you think.  Using them will make your programs better, especially as they get larger, and help you avoid subtle scoping bugs.
--
