== A Browse Through ES6

[%step]
* A Sprint Through ES6

* An ES6 Spike

[NOTE.speaker]
--
Hello everyone. I'm Jez and I'm Chair of the Junior Section of Kings Heath Pickwick Hockey Club. Thanks for coming :)

KHP can trace its history back to mid-1800. The Junior section provides training and competition for kids from ages 4 or 5 upto 16, many of whom go on to play in the senior squads. Over the years our club's produced a number of national league and national squad players. We train on a Sunday morning, and if you're in the South Birmingham area do bring your kids along to have a go. We'd love to see you.

I'm making this rather oblique introduction because I don't want to tout my "experience" as any kind of credential. Over the course of what I laughingly call my career I've had the opportunity to work on a number of interesting things, and with a number (a smaller number) of very good and interesting people. I don't want to claim that what I've done makes me especially, or even particularly, qualified. In the grand scheme of things, I've had a pretty mundane career. Over the past 25 years or so I have, like I guess most of you, written a lot of software that nobody here will have heard of.  Any lawyers, solicitors in the room? Planetary scientists? Midwives? You see?  I'm going to talk today about some things I've learned over the last year or two, and hoepfully they'll be of interest to you and helpful in your mundane careers.

When I first thought about this talk I thought 'A Browse Through ES6' was a nice, gently punning title, but having seen some of the other talks here, I probably should have gone for something more agressive and 'agiley'.  I thought about a sprint, but there's a lot of new stuff in ES6 so I'd end up just firing out words and all end up exhausted and shellshocked.  May a spike would be better - I want to focus on the parts of ES6 that I think are the most useful and significant, and maybe just give some pointers to some of the other bits.  I'm also going to have a look at how you can use ES6 now, today, and into the future.
--

== You Should Leave If ...

[%step]
* JavaScript isn't your thing

* JavaScript is your thing and you're ES6ed up already


[NOTE.speaker]
--
There are four other sessions running right now and if, having heard my introductory burblings, you think you're going to have a better time elsewhere, please do get up and go.  Tjelvar's sessions sounds really fascinating and Burkhard's machine learning is probably going to be good fun, so if you want to go please do, I don't mind and I'd even prefer it.
--

== You Should Stay If ...

[%step]
* JavaScript is your thing

[NOTE.speaker]
--
Are at least one of your things.  I've been working with JavaScript for 20 years and it's almost never been the primary focus or the main language we've been using.  Now obviously over the course of the past few years, and particularly with the emergence of tools like Node.js and client-side frameworks like Ember, Angular, and React, there are more and more people who spent their entire programming time working in JavaScript.  However, my impression is that for most people JavaScript is one of their "other skills".  Is that fair?  Can we take the temperature of the room?  Who is a full-time-no-other-language-shall-cross-my-keyboard JavaScript programmer?  And for everyone else, I assume you're in the "other skills' camp?  What's your main language? Java? C-sharp? C++? What?

So, for you "other skills", you'll have been aware that C-sharp, Java, C++, have all undergone some pretty seisimic changes in the past few years. You might have felt though that while there were lots of interesting things going in JavaScript - libraries like jQuery, lodash, tools like Node, grunt, gulp, frameworks like Ember and so on, there wasn't really anything much going on with JavaScript itself.  JavaScript was JavaScript.  If you wanted language innovation you looked elsewhere - CoffeeScript perhaps, or elsewhere in things like Dart.  But JavaScript was JavaScript and had been for ages.

Spoilers! Not any more, but I guess that's why you're here.
--
