
== But now we have ES6

[%step]
* ES6 fixes none of this

* All our crappy JavaScript will continue to run

* Our new JavaScript can be less crappy


[NOTE.speaker]
--
ES6, officially ECMAScript 6, as ratified as a standard by the good people of the European Computer Manufacturing Association on the 17 June 2015, fixes none of JavaScript's many shortcomings.  ES6 is a superset of ES5, nothing is removed.  Everything that currently runs as JavaScript will continue to run as JavaScript, even if we magically upgraded everybody's browser this evening.

The new JavaScript we're writing though.  That can be less crappy.  Quite a lot less.
--

=== Shiny New Stuff!

Arrow functions

Block scope

Modules

Iterators
  Generators

Promises
  async, await

Parameters
  default parameters
  rest parameters

Destructuring assignement
  spread operator

Template literals

Object literals

Classes, inheritance, proxies, properties

Set, Maps, Arrays

Number, maths

RegExps

Loads!

include::features/let-and-const.adoc[]
include::features/loops.adoc[]
include::features/iterators.adoc[]
include::features/destructure.adoc[]
include::features/parameters.adoc[]
include::features/arrow-functions.adoc[]